import "oaidl.idl";
import "ocidl.idl";
[
	uuid(B5DD61CD-2165-4B3D-BCC0-594C36F9EE06),
	dual,
	object,
	nonextensible,
	pointer_default(unique)
]
interface ICircleAvatar : IDispatch {
	[propget,
		helpstring("Get circle's radius.")] HRESULT Radius(
		[out, retval] float* ReturnVal);

	[propput,
		helpstring("Set circle's raidus.")] HRESULT Radius(
		[in] float Value);

	[propget,
		helpstring("Get circle's image.")] HRESULT ImageFilePath(
		[out, retval] BSTR* ReturnVal);

	[propput,
		helpstring("Set circle's raidus.")] HRESULT ImageFilePath(
		[in] BSTR Value);
};
[
	uuid(E9D304EC-552C-4D89-9804-7AB9E45FEF32),
	version(1.0),
	helpstring("Jichao's Graphics Library"),
]
library GraphicsLibrary {
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	[
		uuid(1C797BFB-3F97-4CF8-B857-45C90028759B),
		helpstring("Circle Avatar")
	]
	coclass CircleAvatar {
		[default] interface ICircleAvatar;
	};
}

